@AlKarmahClub.Api_HostAddress = http://localhost:5053

GET {{AlKarmahClub.Api_HostAddress}}/health
Accept: application/json

###

GET {{AlKarmahClub.Api_HostAddress}}/api/system/status
Accept: application/json

###
